### ISSUE TITLE
Revise and update the design of the project

### ISSUE THREAD

**Issue by ozdenizdolu** [bounswe/bounswe2020group2#114]
We need to make revision on our class, sequence and use-case diagrams. Also we need to make updates if we decide it is necessary.

**Comment by ozdenizdolu** [comment]
I think use-case diagrams are well prepared and do not need to be revised. There are some functions in sequence diagrams that has not added to the class diagrams. If we make sure class diagram is compatible with the sequence diagrams, I think our design is sound.

**Comment by omerfdeniz** [comment]
Updated the previous version of the Use-Case diagram.

**Comment by MehdiSaffar** [comment]
close?
