### ISSUE TITLE
Update Sidebar and Readme for Newcomers 

### ISSUE THREAD

**Issue by abdullahyldz** [bounswe/bounswe2020group2#119]
All newcomers should create a personal page with a small description of themselves and add the links to the sidebar and readme file.

**Comment by abdullahyldz** [comment]
Added my personal link to the sidebar. 
We can update Readme at once when all complete.

**Comment by mcanbayraktar** [comment]
I created my wiki page and linked it to the sidebar.

**Comment by bekir96** [comment]
I created my wiki page and linked it to the sidebar.

**Comment by abdullahyldz** [comment]
Everybody added and I updated Readme.md file.
