### ISSUE TITLE
About issues without proper information

### ISSUE THREAD

**Issue by mericturan** [bounswe/bounswe2020group2#12]
Dear all,

You are mostly OK so far about issues, but I will make a warning just in case.

Please note that each issue should contain **at least one assignee and label**. Besides these, it should also contain **an explanatory title** as well as **a proper description**. Moreover, even though it is not always possible, try to specify the **priority level** and the **deadline** while writing the issues. Last but not least, try to **distribute the issues equally** among team members both in terms of assignee and owner of the issue (i.e., rather than a few people, every single team member should open a sufficient amount of open issues).

Best,
Meriç

**Comment by furkannane** [comment]
Comment above is discussed and noted.
