### ISSUE TITLE
Initialize backend/frontend/mobile repos

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#121]
Create folder structure for all three parts.

**Comment by MehdiSaffar** [comment]
Frontend:

- Created React app
- Added UI framework, configured it to able to change theme
- Added husky pipeline to prettify source code on commit
- Added Dockerfile for deployment
- Added config files and .env files
- Added README.md

PR: https://github.com/bounswe/bounswe2020group2/pull/125

**Comment by asliayk** [comment]
Android:

- Created the Android project
- Added some main dependencies
- Added four empty fragments
- Added bottom navigation bar for these four fragments
- Added empty login fragment
- Added README.md
- Added splash screen
- Added two string files for English and Turkish

PR: https://github.com/bounswe/bounswe2020group2/pull/127
