### ISSUE TITLE
Voting for Color Palette

### ISSUE THREAD

**Issue by asliayk** [bounswe/bounswe2020group2#123]
Everyone should vote on the color palette to be used on our initial prototype, survey link is sent to group members.

**_Due Date: 09.11.2020 Monday @23.59_**

**Comment by MehdiSaffar** [comment]
Voted 2 days ago

**Comment by karalleyna** [comment]
I also voted 2 days ago.

**Comment by MehdiSaffar** [comment]
What is the status on this? What is the chosen color palette?

**Comment by asliayk** [comment]
According to the results, the 3rd palette is selected. Two people didn't vote but as can be seen, the result won't change even if they vote. I will share the palette link on our Slack channel.

<img width="558" alt="palette result" src="https://user-images.githubusercontent.com/56061820/98655865-064d8980-2351-11eb-9c64-1d1a9f8d38a1.PNG">
