### ISSUE TITLE
Studying Kotlin

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#128]
Courses which are listed below had been determined for our needs and level in our Slack channel. In order to rebuild our Android skills, everyone should take a look at these tutorials and share his or status in training. 

1. [Kotlin Bootcamp for Programmers](https://www.udacity.com/course/kotlin-bootcamp-for-programmers--ud9011)
2. [Developing Android Apps with Kotlin](https://www.udacity.com/course/developing-android-apps-with-kotlin--ud9012)
3. [Codelab version of Kotlin Bootcamp for Programmers](https://developer.android.com/codelabs/kotlin-bootcamp-welcome?hl=en#1)
4. [Codelab version of Developing Android Apps with Kotlin](https://codelabs.developers.google.com/codelabs/kotlin-android-training-welcome#2)
5. [Kotlin Coroutines](https://www.youtube.com/watch?v=ShNhJ3wMpvQ&list=PLQkwcJG4YTCQcFEPuYGuv54nYai_lwil_&index=1)

If you have a version of Android Studio lower than 4.0, you can watch this short video 

1. [Installation of Android Studio, Running Emulators and the first Android application](https://www.youtube.com/watch?v=ShNhJ3wMpvQ&list=PLQkwcJG4YTCQcFEPuYGuv54nYai_lwil_&index=1)

**_Due Date: 10.11.2020 Monday @23.59_**

**Comment by karalleyna** [comment]
I reviewed all video tutorials from Udacity.

**Comment by handesirikci** [comment]
i reviewed the kotlin tutorials suggested by the team

**Comment by asliayk** [comment]
I have read tutorials on Codelab and rewatched the coroutines tutorial.
