### ISSUE TITLE
Revision of requirements

### ISSUE THREAD

**Issue by omerfdeniz** [bounswe/bounswe2020group2#13]
Project Requirements should be revisioned by the assignees.

**Comment by omerfdeniz** [comment]
Done

**Comment by handesirikci** [comment]
done

**Comment by hseyyidkaplan** [comment]
Done

**Comment by karalleyna** [comment]
I updated it with Markdown and HTML.

**Comment by MehdiSaffar** [comment]
Reviewed in this commit https://github.com/bounswe/bounswe2020group2/wiki/Project-Requirements/77b61cb1d7f28d3f9efbf66cecd30e4749806724 

I have a question though:

* **Admin:** a ground user that is controlling the system

What is meant by `ground user`?

**Comment by karalleyna** [comment]
> Reviewed in this commit https://github.com/bounswe/bounswe2020group2/wiki/Project-Requirements/77b61cb1d7f28d3f9efbf66cecd30e4749806724
> 
> I have a question though:
> 
> * **Admin:** a ground user that is controlling the system
> 
> What is meant by `ground user`?

After your comment, I rewrote the definition of admin in order to avoid ambiguity

**Comment by MehdiSaffar** [comment]
Thank you @karalleyna.

---

Issue currently waits on https://github.com/bounswe/bounswe2020group2/issues/17 and https://github.com/bounswe/bounswe2020group2/issues/24

**Comment by umutoksuz** [comment]
Done
