### ISSUE TITLE
Deploy Login/SignUp Page 

### ISSUE THREAD

**Issue by mcanbayraktar** [bounswe/bounswe2020group2#132]
## Type of change

- [X] New feature (non-breaking change which adds functionality)

## Description

I will develop Login/SignUp page of the android side.

## Screenshots

No screenshot yet.

## Test Results

No test yet.

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have checked my code and corrected any misspellings
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

**Comment by asliayk** [comment]
Since we couldn't reach @mcanbayraktar , @handesirikci and I started to work on it.
