### ISSUE TITLE
Research about requirements

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#18]
Research about requirements should be done in order to determine whether [requirements](https://github.com/bounswe/bounswe2020group2/wiki/Project-Requirements) of the project are both valid and complete.

**Comment by karalleyna** [comment]
Information about requirements is added.

**Comment by omerfdeniz** [comment]
Done

**Comment by karalleyna** [comment]
After describing requirements, [the research](https://github.com/bounswe/bounswe2020group2/wiki/Requirement-Engineering "the research") is completed.
