### ISSUE TITLE
Search Scenario

### ISSUE THREAD

**Issue by omerfdeniz** [bounswe/bounswe2020group2#23]
Searching scenario is to be created.

**Comment by MehdiSaffar** [comment]
I have prepared the Preconditions and Steps for this scenario. @omerfdeniz can you please check the draft I sent you? Thanks

**Comment by omerfdeniz** [comment]
@MehdiSaffar I checked your draft, revisited Preconditions and Steps and added the Persona and Acceptance Criteria sections. So it is completed.
