### ISSUE TITLE
Questions to the customer

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#24]
Please write all your questions to the customer (if you have any) so that I can ask them in one go.
Question can be related to:
* the name
* the concept of project
* the logo
* the user interface
* the project requirements in general or specific
* etc

I'll start with my question:

1. Are the products sold on the platform have a specific theme (for example only electronics)? Or is it  a general store like Amazon?

**Comment by karalleyna** [comment]
2. Does the platform allow 1-click buying for guest users? Or shall guest users be able to only search,sort and filter products?

**Comment by karalleyna** [comment]
3. Does the platform allow vendors to customize their online shop like [BigCommerce](https://www.bigcommerce.com/ "BigCommerce")? Or is the standard interface used for all vendors' pages like [Hepsiburada](https://www.hepsiburada.com/ "Hepsiburada")?

**Comment by MehdiSaffar** [comment]
Thank you @karalleyna, anyone else have any questions to ask?

**Comment by MehdiSaffar** [comment]
I have asked these questions to the customer, waiting reply.
