### ISSUE TITLE
[ANDROID] Circular Recycler View

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#290]
I could not find any library for creating a circular recycler view. Therefore, I have written on my own. However, this does not meet my expectation. Adding an animation may be a solution but before taking any action, I want to ask whether there is an easy way to implement a circular recycler view or not. 

Here is my current circular recycler view :

https://user-images.githubusercontent.com/36455180/102932570-9551d380-44b1-11eb-8a74-d6a16eba3edf.mov

**Comment by asliayk** [comment]
I liked your idea but I didn't fully understand where you want to use it on the page, is it under the toolbar, or the full screen? I haven't used a circular recycler view before, but we can research it together. However, it looks already good, I didn't understand what do you want to improve about it exactly.

**Comment by karalleyna** [comment]
I have explained what I want to implement to @asliayk in a meeting. We could not find a way to improve the current design. So, we leave this issue at a later time. So, I will close it at now.
