### ISSUE TITLE
Searching Mockup

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#30]
After #23, searching  mockup is created. 

_**Due Date: 03/02/2020 @17.00**_

**Comment by MehdiSaffar** [comment]
Any updates?

**Comment by karalleyna** [comment]
I have resolved the issue but I couldn’t find time to update the wiki as I am attending a conference in London. I will do it tonight.

**Comment by MehdiSaffar** [comment]
@karalleyna  Sounds good! Please let us know when you update the wiki. Thanks
