### ISSUE TITLE
Research favorite repo

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#4]
Explore Github repos and find a good one, explain what it is about and why I picked it.

**Comment by MehdiSaffar** [comment]
I opened this page https://github.com/bounswe/bounswe2020group2/wiki/Repos-we-liked, and added my submission

**Comment by omerfdeniz** [comment]
Review of scikit-learn is added.

**Comment by ozdenizdolu** [comment]
i've added my review

**Comment by furkan-varol** [comment]
Done

**Comment by karalleyna** [comment]
Done.

**Comment by hseyyidkaplan** [comment]
done

**Comment by hseyyidkaplan** [comment]
Please add your comment and then we close. 
@handesirikci @bcetin @umutoksuz @furkannane

**Comment by handesirikci** [comment]
done

**Comment by MehdiSaffar** [comment]
It seems that everybody added their favorite repo. Thank you for your effort.

Closing
