### ISSUE TITLE
Updating with Markdown of Tracking Mockup

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#40]
#39 is done. It is necessary to update [the wiki page](https://github.com/bounswe/bounswe2020group2/wiki/Tracking-Scenario-Mockup)  with Markdown.

**Comment by MehdiSaffar** [comment]
I have given feedback over the Tracking mockup via Slack to @karalleyna. Going to review Searching mockup.

**Comment by MehdiSaffar** [comment]
Reviewed Searching mockup
