### ISSUE TITLE
Incorporate Feedback to Requirements

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#43]
I covered most points in the feedback in this commit https://github.com/bounswe/bounswe2020group2/wiki/Project-Requirements/7909455934d55f73ccc3b7fd845e2f2463c12fe1

Can someone review my changes?

**Comment by umutoksuz** [comment]
I have reviewed last version of the requirements in accordance with given feedback.

Meriç said that we require vendors to specify at least one location info but we didn't show it in 1.1.1.1 registration for vendors. And it is still not shown.
In 1.1.1.3 why customer location info is limited by one. (If we mean address by saying location, then I think a customer should be able to add more than one addresses)

Also Meric said that for 1.1.4.2 when a vendor changes details of a product we need to keep a changelog. I also havent seen it.

If my evaluations are correct, I can edit requirements accordingly.

**Comment by MehdiSaffar** [comment]
for the location the feedback said:

In 1.1.1.1, you share the necessary information to sign-up both for customer and vendor users. However, vendor users are additionally expected to provide their location. You specified it in 1.1.1.3. Yet, it might be forgotten in its current form. Also, vendor users should be able to provide one or more location (but at least one).

so I assumed for vendor (at least one) and for customers (up to one)

I didn't write the location in 1.1.1.1 since the location requirement is different based on whether the user is customer or vendor. I only put the common required information there.

For vendor change details I added that in 

1.2.1.14 Product Details functionality

    1.2.1.15 The system must keep track of the history of product information updates made by Vendors to avoid Vendors changing product information after bad reviews from Customers.

What do you think?

**Comment by umutoksuz** [comment]
I think we can add location to 1.1.1.1 with specifying not mandatory for customer users. Because in the feedback, Meriç said it might be forgotten in its current form.

Limiting customer users with one location is not necessary I think. The other parts are okey In my opinion

**Comment by MehdiSaffar** [comment]
Okay you can edit those parts. Please double check for any typos. That would be great.

**Comment by umutoksuz** [comment]
I have edited those parts. If there wont be additional reviews by other members, we can close the issue.

**Comment by karalleyna** [comment]
I have reviewed user requirements. After I finished reviewing the remaining, we will be able to close this issue.

**Comment by karalleyna** [comment]
- [x]  Removed `such as`  from 1.2.3 and also specified all categories.
- [x]  Handled enumeration failure in System Requirements and updated some part with Markdown.
- [x]  Added `Registered User` to Glossary and to corresponding requirements.

**Comment by MehdiSaffar** [comment]
Hi @karalleyna 
If you believe that the requirements are fully checked, we can close this issue.
