### ISSUE TITLE
[ANDROID] Removal of XML containing key

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#430]
After @asliayk and me made the api key private, map_key.xml was deleted from the master. So, Android Studio gives the following error :

<img width="897" alt="Ekran Resmi 2021-01-23 02 47 53" src="https://user-images.githubusercontent.com/36455180/105560904-50c28d80-5d26-11eb-888d-fef775c2a803.png">

 It should be immediately solved by finding another way to hide the api key. 
_**Deadline : 01.25.2021 @23.59**_

**Comment by asliayk** [comment]
We handled this secret key issue, talked to Meriç Turan and updated our README.md accordingly
