### ISSUE TITLE
[FRONTEND] Test delete product

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#469]
The delete product functionality was dependent on the backend endpoint. When the PR of vendor page was merged, the DELETE endpoint was wrongly implemented (it required the id in the body when DELETE requests cannot have a body). Umut today merged a PR to fix it but the frontend needs to be tested.

**Comment by ozdenizdolu** [comment]
Tested by adding and deleting some products.. It works.
