### ISSUE TITLE
Creating personal Wiki Page

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#5]
Personal Wiki page consists of one of **your photograph** and the following **headers**:

#### 1.About:
It is the summary part of your education, experience and interests.
#### 2.Skills:
It includes your technical skills and endorsements which can be helpful for this project.
#### 3.Contact:
It contains any links to your personal web pages such as Linkedin, etc. and your email address.

#### Due Date: 02/17/2020 @23.59 *by*
*@omerfdeniz @handesirikci @MehdiSaffar @vaveylafv  @ozdenizdolu @bcetin @kuscu44 @karalleyna @furkannane @umutoksuz*

> ######  #3 is related to this issue.

**Comment by karalleyna** [comment]
Done.

**Comment by karalleyna** [comment]
@furkannane Your personal page links to your previous group, please correct.

**Comment by omerfdeniz** [comment]
Done.

**Comment by furkan-varol** [comment]
Done

**Comment by MehdiSaffar** [comment]
Done

**Comment by handesirikci** [comment]
done

**Comment by ozdenizdolu** [comment]
done

**Comment by hseyyidkaplan** [comment]
done
