### ISSUE TITLE
Communication Channel

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#50]
According to our **"new life"** after the covid-19 pandemics, we must change our methods of handling the meeting plan. How about using Zoom as a communication channel for weekly meeting?

**Comment by furkannane** [comment]
I absolutely agree with you. We need to come up with a plan. I am not sure if online meetings are effective but we can try .

**Comment by asliayk** [comment]
I agree with you too, we can collaborate better by this way.

**Comment by omerfdeniz** [comment]
Zoom is a great choice for the task, it will definitely help us.

**Comment by handesirikci** [comment]
zoom is okay for communicating, i also suggest to use sketchboard[https://sketchboard.io/](url) to design and visual support. it has software sketching tools, would help us also

**Comment by MehdiSaffar** [comment]
Sure, Zoom or Google Meet is good.

**Comment by bcetin** [comment]
I would prefer discord + something like sketchboard.io for common visuals but ok with the Zoom proposal as well.

**Comment by ozdenizdolu** [comment]
@bcetin  +1 common visuals would be really helpful

**Comment by hseyyidkaplan** [comment]
zoom is ok for me
