### ISSUE TITLE
Slogan for Getflix

### ISSUE THREAD

**Issue by asliayk** [bounswe/bounswe2020group2#51]
I think we can all think of a short and catchy slogan for our platform, it can be written under our logo or maybe we can use it as a tab title.

**Comment by bcetin** [comment]
Get what you want!

**Comment by hseyyidkaplan** [comment]
> Get what you want!

so stereotype

**Comment by hseyyidkaplan** [comment]
I have a suggestion for name, tagline and logo though your decision first. 
![image](https://user-images.githubusercontent.com/32467338/78079614-1d88c980-73b5-11ea-876a-00b176095001.png)

**Comment by hseyyidkaplan** [comment]
I thought that it is very remindable and Brand name makes a sentence such a suggestion with catchword. If you approve the logo can be changed

**Comment by hseyyidkaplan** [comment]
any comment?

> I thought that it is very remindable and Brand name makes a sentence such a suggestion with catchword. If you approve the logo can be changed

**Comment by MehdiSaffar** [comment]
I like it, it is quite catchy. What does the icon/logo represent though?

**Comment by karalleyna** [comment]
I think that Pazardan is not convenient for global company. Getflix may not be the best option for the name but it sounds better.

**Comment by hseyyidkaplan** [comment]
> I think that Pazardan is not convenient for global company. Getflix may not be the best option for the name but it sounds better.

Is english name necessary for global company. For example Alibaba is a global company. Getflix is like 'did you mean netflix'

**Comment by hseyyidkaplan** [comment]
> I like it, it is quite catchy. What does the icon/logo represent though?

It is like 'drop by drop becomes lake' (damlaya damlaya göl olur). When we save money such water in dam, it can be useful thing for us like flowing water through tap. Such like open the tap and use water as you need. Logo will ring the the bell by people that you can buy whatever you need with your savings

**Comment by karalleyna** [comment]
> > I think that Pazardan is not convenient for global company. Getflix may not be the best option for the name but it sounds better.
> 
> Is english name necessary for global company. For example Alibaba is a global company. Getflix is like 'did you mean netflix'

No, it is not must but Pazardan is meaningless without it's slogan and slogan part cannot be understood by people not knowing Turkish. Also, i think that slogan is like short description of your company and you can influence people and describe your company only if you are in line with the majority.

**Comment by hseyyidkaplan** [comment]
> > > I think that Pazardan is not convenient for global company. Getflix may not be the best option for the name but it sounds better.
> > 
> > 
> > Is english name necessary for global company. For example Alibaba is a global company. Getflix is like 'did you mean netflix'
> 
> No, it is not must but Pazardan is meaningless without it's slogan and slogan part cannot be understood by people not knowing Turkish. Also, i think that slogan is like short description of your company and you can influence people and describe your company only if you are in line with the majority.

ok but in getflix option also slogan is not captured by people who dont know english.

**Comment by asliayk** [comment]
I've thought getflix is already chosen and created some logos for it, and also shortened Burak's slogan to "get all you want" because of the character limit on the website.
I also think an English name is better but maybe we can create polls for a name and logo. But if we choose getflix, I think we shouldn't use red-black combination for logo design, it's really very similar to Netflix.
I've used the website looka.com, you can also design on it, it's really easy to use. Here are my logos: 

1) ![cats6](https://user-images.githubusercontent.com/56061820/78891830-ebd8c800-7a70-11ea-9eac-31d4850abeb4.jpg)

2) ![cats8](https://user-images.githubusercontent.com/56061820/78891841-eda28b80-7a70-11ea-8c70-0b88268d1c1d.jpg)

3) ![cats7](https://user-images.githubusercontent.com/56061820/78891846-ef6c4f00-7a70-11ea-9e9c-e8f2b61dd220.jpg)

4) ![cats3](https://user-images.githubusercontent.com/56061820/78891849-f1361280-7a70-11ea-81e3-fbb35394b8f5.jpg)

5) ![cats5](https://user-images.githubusercontent.com/56061820/78891852-f3986c80-7a70-11ea-964f-993592212fad.jpg)

**Comment by hseyyidkaplan** [comment]
O think 1st and last ones are good

**Comment by hseyyidkaplan** [comment]
But last one is more preferable for our project. The first one is more likely be interpreted as stock exchange app

**Comment by karalleyna** [comment]
I used the website @asliayk shared and created some additional logos.
1. <img width="433" alt="Ekran Resmi 2020-04-16 23 33 16" src="https://user-images.githubusercontent.com/36455180/79505890-c4b86280-803d-11ea-96e3-4dcdd68ecadb.png">
2. <img width="403" alt="Ekran Resmi 2020-04-16 23 34 00" src="https://user-images.githubusercontent.com/36455180/79505912-cd109d80-803d-11ea-8484-57b477cd6ac8.png">
3. <img width="384" alt="Ekran Resmi 2020-04-16 23 50 00" src="https://user-images.githubusercontent.com/36455180/79505941-d4d04200-803d-11ea-9af5-0201e2507ca5.png">
4. <img width="324" alt="Ekran Resmi 2020-04-16 22 49 15" src="https://user-images.githubusercontent.com/36455180/79505957-dbf75000-803d-11ea-8d75-fe732367b203.png">
5. <img width="441" alt="Ekran Resmi 2020-04-16 22 55 57" src="https://user-images.githubusercontent.com/36455180/79505843-b79b7380-803d-11ea-92d5-234f51d2d1c7.png">
6. <img width="436" alt="Ekran Resmi 2020-04-16 22 53 18" src="https://user-images.githubusercontent.com/36455180/79505854-b9fdcd80-803d-11ea-8374-cacc7d0ce3c0.png">
7. <img width="506" alt="Ekran Resmi 2020-04-16 22 58 28" src="https://user-images.githubusercontent.com/36455180/79505944-d69a0580-803d-11ea-823e-2af9a789cdd2.png">

**Comment by asliayk** [comment]
Slogan is chosen(if getflix is okay) and logo ideas are determined.
