### ISSUE TITLE
Revision of the First Part of Project Plan

### ISSUE THREAD

**Issue by karalleyna** [bounswe/bounswe2020group2#55]
The first part of the project plan will be completed by @furkannane and reviewed by assignees. 
**_Deadline: 04/21/2020_  @23.55**

**Comment by karalleyna** [comment]
These tasks must be added to the first part of the project plan. References are included in order to not only specify reason and time but also determine who has contributed to corresponding task. 


|No | Task  |Begin Time| Finish Time| People|References |
| ----| ------------- | ------------- |------------- |------------- |------------- |
| 1 | Creating slack space   | 13.02.2020  | 17.02.2020  | Mehdi Saffar|  #1   |
| 2 | Git and Github Research | 13.02.2020 | 17.02.2020  | Mehdi Saffar and Özdeniz Dolu| [commits](https://github.com/bounswe/bounswe2020group2/wiki/Git-and-Github/_history) |
| 3 | Studying Git and Github | 13.02.2020  | 17.02.2020  | Everyone  |   |
| 4| Requirement Engineering Research  | 18.02.2020  | 25.02.2020 | Aleyna Kara  | #18, [commits](https://github.com/bounswe/bounswe2020group2/wiki/Requirement-Engineering)  |
| 5| Revision of Requirements  | 18.02.2020  | 25.02.2020  | Ömer Faruk Deniz, Hande Şirikçi, Hüseyin Seyyid Kaplan, Aleyna Kara, Mehdi Saffar and Umut Öksüz  | #13, #17 , #24 , [commits](https://github.com/bounswe/bounswe2020group2/wiki/Project-Requirements/_history) |
| 6 | Preparing Questions to Customers | 25.02.2020  | 02.03.2020 | Mehdi Saffar and Aleyna Kara | #24   |
| 7 | Communication Plan Revision | 25.02.2020  | 02.03.2020  | Furkan Nane  | #28  |
| 8 | Meeting Notes  Revision | 25.02.2020  | 02.03.2020  | Aleyna Kara  | #31   |
| 9 | Customer Meeting | 02.03.2020  | 03.03.2020  | Mehdi Saffar and Furkan Nane  |   |
| 10 | Tracking Mockup | 27.02.2020  | 03.03.2020  | Özdeniz Dolu  | [commits](https://github.com/bounswe/bounswe2020group2/wiki/Tracking-Scenario-Mockup)  |
| 11 | Purchasing Mockup | 27.02.2020  | 03.03.2020  | Hüseyin Seyyid Kaplan  | [commits](https://github.com/bounswe/bounswe2020group2/wiki/Purchasing-Scenario-Mockup)   |
| 12 | Searching Mockup | 27.02.2020  | 03.03.2020  | Aleyna Kara  | #30, #44, [commits](https://github.com/bounswe/bounswe2020group2/wiki/Searching-Scenario-Mockup)   |
| 13 | Revision of Tracking Mockup | 08.03.2020 | 12.03.2020  | Aleyna Kara  | #39 , #40 ,  [commits](https://github.com/bounswe/bounswe2020group2/wiki/Tracking-Scenario-Mockup) |
| 14 | Sequence Diagram | 08.04.2020 | 24.03.2020  |  Ömer Faruk Deniz, Umut Öksüz,Aleyna Kara and Özdeniz Dolu  |  #45, #53, [commits](https://github.com/bounswe/bounswe2020group2/wiki/Sequence-Diagrams) |
| 15 | Studying requirements | 28.03.2020 | 02.04.2020  | Aslı Aykan |  |
| 16 | Studying Scenarios | 28.03.2020 | 02.04.2020  | Aslı Aykan |  |
| 17 | Studying Mockups | 28.03.2020 | 02.04.2020  | Aslı Aykan |  |
| 18 | Revision of Git and Github Research| 28.03.2020 | 02.04.2020  | Aslı Aykan  | #48, [commits](https://github.com/bounswe/bounswe2020group2/wiki/Git-and-Github) |
| 19 | Revision of Searching Scenario | 28.03.2020 | 02.04.2020  | Aslı Aykan | #49, [commits](https://github.com/bounswe/bounswe2020group2/wiki/User-Scenario-%233:-Searching) |

**Comment by MehdiSaffar** [comment]
With the help of @umutoksuz, we integrated these changes. The project plan is available through [this link](https://raw.githubusercontent.com/bounswe/bounswe2020group2/master/images/output.png) or in the wiki sidebar under Project > Project Plan
