### ISSUE TITLE
Voting for Logo

### ISSUE THREAD

**Issue by asliayk** [bounswe/bounswe2020group2#57]
Everyone should vote on the logo, survey link is sent to group members.

**Comment by MehdiSaffar** [comment]
Voted

**Comment by hseyyidkaplan** [comment]
voted

**Comment by omerfdeniz** [comment]
Voted

**Comment by asliayk** [comment]
According to results, 8 is chosen as our logo.
<img width="452" alt="result" src="https://user-images.githubusercontent.com/56061820/80109127-ccb85b00-8585-11ea-96ec-6a4a3e264ac1.PNG">

<img width="433" alt="79505890-c4b86280-803d-11ea-96e3-4dcdd68ecadb" src="https://user-images.githubusercontent.com/56061820/80109473-333d7900-8586-11ea-8c35-7cf98ce3af7d.png">
