### ISSUE TITLE
Compile Project Plan into Gantt chart

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#58]
Create the Gantt chart that shows the different tasks grouped into milestones.

Deadline: 20.04.2020 Monday @23.59

**Comment by MehdiSaffar** [comment]
First draft:

![output](https://user-images.githubusercontent.com/13124263/79657950-f48d7480-81bb-11ea-88c1-89f6c70f1afe.png)

@asliayk @karalleyna can you take a look and see if anything needs to change?

**Comment by asliayk** [comment]
Logo design can be added. Me, @karalleyna and @kuscu44 have designed some logos for survey.

**Comment by MehdiSaffar** [comment]
Thank you @asliayk. I added the logo design task as well as the changes in the issue https://github.com/bounswe/bounswe2020group2/issues/55#issuecomment-615809492

Here is the final version (v1):

![output](https://user-images.githubusercontent.com/13124263/79697176-eb6ad900-8289-11ea-8c2f-bfa34e819d0c.png)
