### ISSUE TITLE
Do research and think on API assignment.

### ISSUE THREAD

**Issue by ozdenizdolu** [bounswe/bounswe2020group2#63]
Discuss your ideas on the topics raised in API assignment. Make suggestions. Share your knowledge.

**Comment by MehdiSaffar** [comment]
I have some experience with using Javascript so my opinion will be biased towards that.

The goal of the assignment is to have some backend on an Amazon EC3 instance (basically a server). We will ask the backend to do something and it will do it on our behalf by asking another third-party API. Third-party API could be a location service, a weather service, some search service etc.

## Language 

I think Javascript would be really good for this task

- Minimal requirements: We only need to install Node.js and Node Package Manager (npm) on the server. Can be done very easily:

```
curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.0/install.sh | bash
./nvm/nvm.sh
nvm install <whatever-version>
```

- Can be easily tested locally with a tool like `nodemon` that allows for quick reloading whenever you change the code
- Has really good unit test libraries such as `mocha`
- Most third-party APIs use JSON (Javascript Object Notation) so JS is the most suitable for manipulating such data
- It is overall intuitive and easy to use

## IDE

I would recommend `visual studio code`. It is very user friendly and customizable a lot, especially when it comes to web development.

## Version control

`git` of course. It would be nice to use something like `git flow` to keep track of the features in our code branches.

## Frontend

The frontend could also be written in Javascript in the browser. So a simple page with buttons and input boxes (depending on what our API will be). React or something similar could be used as a framework.

## Other tools

`postman` is a nice tool to use to send HTTP requests to an API to discover it or test it. It is available on all platforms.

Let me know what you think?

**Comment by ozdenizdolu** [comment]
I love your suggestions. I don't have a lot of experience on back-end but i am comfortable with using JavaScript. Therefore, I prefer JavaScript too.

I also love vscode so i think it's a good suggestion.

I don't know about `postman`, so i'll take your suggestion.

My 3rd Party API suggestions:
Google Map
Masterpass
