### ISSUE TITLE
Prepare Evaluation of Tools and Processes of Milestone 1 Report

### ISSUE THREAD

**Issue by MehdiSaffar** [bounswe/bounswe2020group2#71]
The following have to done:

**Evaluation of Tools and Processes**: 
    - **ProjectLibre**: Mehdi Saffar
    - **Lucidchart**: Aleyna Kara
    - **Balsemic**: Aleyna Kara
    - **Excel**: Aslı Aykan
    - **Slack & Zoom vs.**: Furkan Nane

**Comment by MehdiSaffar** [comment]
Added ProjectLibre review

**Comment by karalleyna** [comment]
- [x]  Balsamiq and Lucidchart review.

**Comment by asliayk** [comment]
Added the Excel review.
