### ISSUE TITLE
Implement the location and currency update functionality of the API and create basic front-end to demonstrate

### ISSUE THREAD

**Issue by ozdenizdolu** [bounswe/bounswe2020group2#79]
we are assigned to add "getting updated prices with respect to the currency of the client's location" function to our API also we need to come up with a front end

**Comment by ozdenizdolu** [comment]
I have created a branch named "locationcurrencyapi". I have added /api/getUpdatedPrice route to our API. When it get's an IP value called "ip" as a get request, it responses with the currency of the country that that IP belongs to(using a 3rd party api). Hande will implement product price calculations using another third party api.

**Comment by handesirikci** [comment]
I reviewed and understood what Ozdeniz did for the first part. By using a 3rd party api i added the functionality of returning current value of given currency type and calculated the price of this product by using this value. it gets currency type and responses calculated price of the product

**Comment by ozdenizdolu** [comment]
Due to the long period of waiting, we decided to delete the previous branch and create a new one. We will consider the reviews on our previous pull request and create a better branch with full functionality.

**Comment by ozdenizdolu** [comment]
After both reviews on pull requests #78  and #85 , we have completed the task and finally merged to master.
